title: Indatable CV
description: Les consultants Indatable

url: https://cv.indatable.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
